#if canImport(FoundationModels)
import Foundation
import FoundationModels

/// Tier-1 LLM adapter: Apple **Foundation Models** (PRD §9.3). Zero download, free, on-device
/// (Apple Intelligence). Uses **guided generation** (`@Generable`) so the model returns typed
/// structs instead of free text we'd have to parse.
///
/// Design decisions baked in here (see docs/DECISIONS.md D12–D14):
///  • **Timestamps are never generated by the model** — the LLM produces titles/labels only; all ms
///    values are anchored structurally from window/segment bounds. LLMs are unreliable at exact
///    timestamps; anchoring makes chapters/key-moments provably land on real audio positions.
///  • **A fresh session per map window** — no cross-window context bleed; each window judged clean.
///  • **Reduce consumes compact per-window notes**, not the raw transcript, so it fits the ~4,096
///    token context even for a 3h episode.
@available(macOS 26.0, iOS 26.0, *)
public struct FoundationModelsIntelligence: EpisodeIntelligenceEngine {
    public let identifier: String
    public let contextTokenLimit: Int
    public var approxResidentBytes: Int { 0 } // OS-resident model; not counted against our footprint

    public init(identifier: String = "apple-foundation-models", contextTokenLimit: Int = 4096) {
        self.identifier = identifier
        self.contextTokenLimit = contextTokenLimit
    }

    public enum EngineError: Error, CustomStringConvertible {
        case unavailable(String)
        public var description: String {
            switch self { case .unavailable(let r): return "Foundation Models unavailable: \(r)" }
        }
    }

    /// All sessions use the **permissive content-transformation guardrails** (E11/E12 root fix).
    /// Apple ships this mode specifically for apps that transform user-provided content
    /// (summarization/classification of transcripts is the canonical case). Default guardrails were
    /// refusing ordinary podcast content — 3 of 7 real episodes across biography/finance/history.
    static let permissiveModel = SystemLanguageModel(guardrails: .permissiveContentTransformations)

    /// Fail fast (and clearly) if Apple Intelligence isn't ready — the caller falls back to Tier 2.
    public func load() async throws {
        switch SystemLanguageModel.default.availability {
        case .available: return
        case .unavailable(let reason): throw EngineError.unavailable("\(reason)")
        }
    }

    // MARK: Guided-generation mirrors (kept private so core types stay framework-free)

    @Generable
    struct WindowNotesGen {
        @Guide(description: "A 3–6 word topic label for this passage")
        var topicLabel: String
        @Guide(description: "2–4 concise factual key points a listener should remember")
        var salientPoints: [String]
        @Guide(description: "0–2 short verbatim quotable lines, or empty if none stand out")
        var quotableLines: [String]
    }

    @Generable
    struct DigestGen {
        @Guide(description: "A 1–2 sentence TL;DR of the whole episode")
        var tldr: String
        @Guide(description: "3–5 actionable takeaways")
        var takeaways: [String]
        @Guide(description: "Ordered topic-based chapter titles, one per major theme")
        var chapterTitles: [String]
        @Guide(description: "3–5 highlight titles for the most notable moments")
        var keyMomentTitles: [String]
    }

    @Generable
    struct SnipGen {
        @Guide(description: "One of: insight, quote, takeaway, question, story")
        var category: String
        @Guide(description: "A punchy 4–8 word title")
        var title: String
        @Guide(description: "2 short bullet takeaways")
        var bullets: [String]
        @Guide(description: "The excerpt lightly cleaned of filler words, meaning unchanged")
        var cleanedExcerpt: String
    }

    // MARK: MAP

    public func mapWindow(_ window: TranscriptWindow) async throws -> WindowNotes {
        let instructions = """
            You analyze one passage of a podcast transcript. Be terse and factual. Do not invent
            content that isn't present. Mark sponsor reads / advertisements accurately.
            """
        let prompt = "Passage:\n\(window.text)"

        // Guided generation first (typed output). E16: guided generation REFUSES real transcript
        // content that plain generation on the same session/model/text accepts — verified 12/12 vs
        // 0/12 in controlled probes, deterministic per text. So on refusal, fall back to a plain
        // respond() with a strict line format and parse it — same information, different decode path.
        do {
            let session = LanguageModelSession(model: Self.permissiveModel, instructions: instructions)
            let gen = try await session.respond(to: prompt, generating: WindowNotesGen.self).content
            return WindowNotes(windowId: window.id, startMs: window.startMs, endMs: window.endMs,
                               topicLabel: gen.topicLabel, salientPoints: gen.salientPoints,
                               quotableLines: gen.quotableLines)
        } catch {
            let session = LanguageModelSession(model: Self.permissiveModel, instructions: instructions)
            let reply = try await session.respond(to: """
                \(prompt)

                Respond in EXACTLY this line format (no other text):
                TOPIC: <3-6 word topic label>
                POINT: <key point 1>
                POINT: <key point 2>
                QUOTE: <one short quotable line, or omit>
                """).content
            var topic = "Untitled section"
            var points: [String] = []
            var quotes: [String] = []
            for line in reply.split(separator: "\n") {
                let l = line.trimmingCharacters(in: .whitespaces)
                if l.hasPrefix("TOPIC:") { topic = String(l.dropFirst(6)).trimmingCharacters(in: .whitespaces) }
                else if l.hasPrefix("POINT:") { points.append(String(l.dropFirst(6)).trimmingCharacters(in: .whitespaces)) }
                else if l.hasPrefix("QUOTE:") { quotes.append(String(l.dropFirst(6)).trimmingCharacters(in: .whitespaces)) }
            }
            return WindowNotes(windowId: window.id, startMs: window.startMs, endMs: window.endMs,
                               topicLabel: topic, salientPoints: points, quotableLines: quotes)
        }
    }

    // MARK: REDUCE

    public func reduce(notes: [WindowNotes], adFreeText: String) async throws -> EpisodeDigest {
        // Build a compact, ad-free brief from the per-window notes (already ad-filtered upstream).
        let brief = notes.map { n in
            "• [\(msToClock(n.startMs))] \(n.topicLabel): \(n.salientPoints.joined(separator: "; "))"
        }.joined(separator: "\n")
        let instructions = """
            You synthesize an episode-level digest from ordered per-section notes. Titles only —
            never fabricate timestamps or quote content not in the notes.
            """
        let promptBody = "Section notes (chronological):\n\(brief)"

        // Guided first; plain-format fallback on refusal (E16 — same rationale as mapWindow).
        var tldr: String, takeaways: [String], chapterTitles: [String], keyMomentTitles: [String]
        do {
            let session = LanguageModelSession(model: Self.permissiveModel, instructions: instructions)
            let gen = try await session.respond(to: promptBody, generating: DigestGen.self).content
            (tldr, takeaways, chapterTitles, keyMomentTitles) = (gen.tldr, gen.takeaways, gen.chapterTitles, gen.keyMomentTitles)
        } catch {
            let session = LanguageModelSession(model: Self.permissiveModel, instructions: instructions)
            let reply = try await session.respond(to: """
                \(promptBody)

                Respond in EXACTLY this line format (no other text):
                TLDR: <1-2 sentence summary>
                TAKEAWAY: <takeaway>
                CHAPTER: <chapter title>
                MOMENT: <key moment title>
                (repeat TAKEAWAY/CHAPTER/MOMENT lines as needed)
                """).content
            tldr = ""; takeaways = []; chapterTitles = []; keyMomentTitles = []
            for line in reply.split(separator: "\n") {
                let l = line.trimmingCharacters(in: .whitespaces)
                if l.hasPrefix("TLDR:") { tldr = String(l.dropFirst(5)).trimmingCharacters(in: .whitespaces) }
                else if l.hasPrefix("TAKEAWAY:") { takeaways.append(String(l.dropFirst(9)).trimmingCharacters(in: .whitespaces)) }
                else if l.hasPrefix("CHAPTER:") { chapterTitles.append(String(l.dropFirst(8)).trimmingCharacters(in: .whitespaces)) }
                else if l.hasPrefix("MOMENT:") { keyMomentTitles.append(String(l.dropFirst(7)).trimmingCharacters(in: .whitespaces)) }
            }
            if tldr.isEmpty && takeaways.isEmpty { throw error }   // fallback produced nothing usable
        }

        // Anchor chapter/moment timestamps structurally to the notes we actually have.
        let chapters = anchorChapters(titles: chapterTitles, notes: notes)
        let keyMoments = anchorKeyMoments(titles: keyMomentTitles, notes: notes)
        let summary = EpisodeSummary(tldr: tldr, takeaways: takeaways)
        return EpisodeDigest(summary: summary, keyMoments: keyMoments, chapters: chapters)
    }

    // MARK: SNIP ENRICHMENT

    public func enrichSnip(_ request: SnipEnrichmentRequest) async throws -> SnipEnrichment {
        let instructions = """
            You turn a saved podcast excerpt into a shareable snip card. Faithful, punchy, no hype.
            """
        // Clamp the excerpt to the model's context (a snip should be ~30-60s of speech, but the
        // caller may hand us more; measured live: an unclamped excerpt overflowed the 4,096-token
        // window). ~4 chars/token; leave room for instructions + output.
        let excerpt = String(request.excerpt.prefix(10_000))
        let prompt = "Excerpt:\n\(excerpt)"

        // Guided first; plain line-format fallback on refusal (D24/E16 — measured live on the
        // enrich path too: 4 of 9 real-corpus probe excerpts were refused under guided generation).
        do {
            let session = LanguageModelSession(model: Self.permissiveModel, instructions: instructions)
            let gen = try await session.respond(to: prompt, generating: SnipGen.self).content
            let category = SnipEnrichment.Category(rawValue: gen.category.lowercased()) ?? .insight
            return SnipEnrichment(category: category, title: gen.title,
                                  bullets: gen.bullets, cleanedExcerpt: gen.cleanedExcerpt)
        } catch {
            let session = LanguageModelSession(model: Self.permissiveModel, instructions: instructions)
            let reply = try await session.respond(to: """
                \(prompt)

                Respond in EXACTLY this line format (no other text):
                CATEGORY: <one of insight|quote|takeaway|question|story>
                TITLE: <punchy 4-8 word title>
                BULLET: <takeaway 1>
                BULLET: <takeaway 2>
                """).content
            var category = SnipEnrichment.Category.insight
            var title = ""
            var bullets: [String] = []
            for line in reply.split(separator: "\n") {
                let l = line.trimmingCharacters(in: .whitespaces)
                if l.hasPrefix("CATEGORY:") {
                    category = SnipEnrichment.Category(
                        rawValue: String(l.dropFirst(9)).trimmingCharacters(in: .whitespaces).lowercased()) ?? .insight
                } else if l.hasPrefix("TITLE:") {
                    // Plain-mode models sometimes emit markdown emphasis; card faces want bare text.
                    title = String(l.dropFirst(6)).trimmingCharacters(in: .whitespaces)
                        .replacingOccurrences(of: "*", with: "")
                        .trimmingCharacters(in: .whitespaces)
                } else if l.hasPrefix("BULLET:") {
                    bullets.append(String(l.dropFirst(7)).trimmingCharacters(in: .whitespaces))
                }
            }
            if title.isEmpty { throw error }   // fallback produced nothing usable
            // Cleaned excerpt is a nicety; on the fallback path keep the raw excerpt (faithful > clever).
            return SnipEnrichment(category: category, title: title, bullets: bullets, cleanedExcerpt: excerpt)
        }
    }

    // MARK: SPEAKER NAMING

    public func nameSpeakers(introText: String, clusters: [String]) async throws -> [String: String] {
        // Conservative: label the first two clusters Host/Guest; only override if the intro is clear.
        var map: [String: String] = [:]
        for (i, c) in clusters.enumerated() { map[c] = i == 0 ? "Host" : (i == 1 ? "Guest" : "Speaker \(i + 1)") }
        return map
    }

    // MARK: - Structural timestamp anchoring (model produces titles; we place them in time)

    private func anchorChapters(titles: [String], notes: [WindowNotes]) -> [Chapter] {
        guard !notes.isEmpty, !titles.isEmpty else { return [] }
        // Distribute chapter titles evenly across the ordered notes' time span.
        let stride = max(1, notes.count / titles.count)
        var chapters: [Chapter] = []
        for (i, title) in titles.enumerated() {
            let startNote = notes[min(i * stride, notes.count - 1)]
            let endMs = (i + 1 < titles.count) ? notes[min((i + 1) * stride, notes.count - 1)].startMs : (notes.last?.endMs ?? startNote.endMs)
            chapters.append(Chapter(title: title, startMs: startNote.startMs, endMs: max(endMs, startNote.endMs)))
        }
        return chapters
    }

    private func anchorKeyMoments(titles: [String], notes: [WindowNotes]) -> [KeyMoment] {
        guard !notes.isEmpty else { return [] }
        // Place each key moment at the note whose salient content best matches its title (keyword
        // overlap) — but anchor it to a 60s window around the note's MIDPOINT, not the whole note.
        // A note spans 10–20 minutes; a "moment" that wide overlapped some ad range on virtually
        // every real episode, so the ad-exclusion validation (correctly) dropped every key moment
        // the model produced. Measured on the 7-episode corpus: keyMoments were empty on 7/7 runs
        // before this fix (D30).
        return titles.map { title in
            let best = notes.max { a, b in matchScore(title, a) < matchScore(title, b) } ?? notes[0]
            let mid = (best.startMs + best.endMs) / 2
            return KeyMoment(title: title,
                             startMs: max(best.startMs, mid - 30_000),
                             endMs: min(best.endMs, mid + 30_000))
        }
    }

    private func matchScore(_ title: String, _ note: WindowNotes) -> Int {
        let words = Set(Scoring.normalizeWords(title))
        let hay = Set(Scoring.normalizeWords(note.topicLabel + " " + note.salientPoints.joined(separator: " ")))
        return words.intersection(hay).count
    }

    private func msToClock(_ ms: Int) -> String {
        let s = ms / 1000; return String(format: "%d:%02d", s / 60, s % 60)
    }
}
#endif
